# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Melonz's blog
email: support@melonz.nl
description: The official blog of Melonz. We post about ourselves (because we have an ego) and tech sometimes.
baseurl: ""
url: https://blog.melonz.nl
urlnp: blog.melonz.nl
twitter: https://twitter.com/melonzinc
github: https://github.com/Melonz/melonz.github.io
permalink: /:year/:title.html

markdown: kramdown
kramdown:
  input: GFM
  
highlighter: rouge
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
